vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v01.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v02.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v03.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v04.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v05.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v06.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v07.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v08.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v09.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v10.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v11.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v12.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v13.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v14.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v15.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v16.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v17.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v18.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v19.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v20.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\v21.avi
vid2vec D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\0-10.avi
