lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\0-10.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\0-10.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v01.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v01.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v02.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v02.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v03.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v03.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v04.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v04.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v05.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v05.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v06.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v06.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v07.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v07.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v08.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v08.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v09.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v09.pb.csv                
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v10.csv                   
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v11.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v11.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v12.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v12.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v13.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v13.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v14.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v14.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v15.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v15.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v16.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v16.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v17.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v17.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v18.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v18.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v19.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v19.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v20.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v20.pb.csv  
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v21.csv     
lfa -q -s -m 4 D:\GoogleDrive-VMS\Research\lip-reading\datasets\angsawee\avi\run-2021-07-20\v21.pb.csv  