python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v01 (File responses)" v01 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v02 (File responses)" v02 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v03 (File responses)" v03 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v04 (File responses)" v04 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v05 (File responses)" v05 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v06 (File responses)" v06 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v07 (File responses)" v07 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v08 (File responses)" v08 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v09 (File responses)" v09 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v10 (File responses)" v10 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v11 (File responses)" v11 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v12 (File responses)" v12 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v13 (File responses)" v13 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v14 (File responses)" v14 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v15 (File responses)" v15 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v16 (File responses)" v16 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v17 (File responses)" v17 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v18 (File responses)" v18 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v19 (File responses)" v19 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v20 (File responses)" v20 output
python rename.py "D:\GoogleDrive-VMS\Thai Lipreading Research Participation (File responses)\v21 (File responses)" v21 output
